[package]
name = "lflc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
deflate = "1.0.0"
base64 = "0.21.5"
anyhow = "1.0.75"
phf = { version = "0.11.2", features = ["macros"] }
